### ISSUE TITLE
Import fixes from https://github.com/Contrast-Security-Inc/esprima

### ISSUE THREAD

**Issue by jogibear9988** [node-projects/esprima-next#6]
https://github.com/Contrast-Security-Inc/esprima has many fixes not in our fork, look for them.

https://github.com/jquery/esprima/compare/main...Contrast-Security-Inc:master

- [x] backport old javascript patches into typescript
- [x] add parser support for optional try / catch binding as seen in TC39/t… …
- [x] adjust node type for catchclause to support null arguments for non-as… …
- [x] add associated test
- [x] var -> let
- [x] add es6 flag because TS continuous integration will fail otherwise (e… …
- [x] update whitelist
- [x] Merge remote-tracking branch 'origin/master' into NODE-957
- [x] remove deceptive jsdoc and fix function to adhere
- [x] Merge pull request #1 from Contrast-Security-Inc/NODE-957 …
- [x] move to @contrast/esprima
- [x] Merge branch 'master' of github.com:contrast-security-inc/esprima int… …
- [x] update package.json to use 4.0 tag
- [x] add optional chaining support
- [x] fix indentation
- [x] add parsing support for nullish coalescing
- [x] fix indentation
- [x] Merge pull request #2 from Contrast-Security-Inc/optional-chaining …
- [x] 4.1.0
- [x] fixed issue with optional chaining conflating decimal numbers in a …
- [x] undid tab
- [x] Merge branch 'hotfix/NODE-1126-fix-nullish-coalesce'
- [x] remove unnecessary dependencies and audit fix all but one low severit… …
- [x] Merge pull request #4 from Contrast-Security-Inc/NODE-1546-bump …
- [x] 4.1.1
- [x] 4.1.2

**Comment by jogibear9988** [comment]
about this commit:

 backport old javascript patches into typescript

is this valid? I did not find classproperty in estree specification

**Comment by jogibear9988** [comment]
maybe in Es2022 https://github.com/estree/estree/blob/master/es2022.md

**Comment by Meir017** [comment]
> maybe in Es2022 https://github.com/estree/estree/blob/master/es2022.md

chrome already support private members
![image](https://user-images.githubusercontent.com/9786571/122083887-f37cc500-ce09-11eb-90eb-301c61d6ddf7.png)
```js
class IncreasingCounter {
  #count = 0;
  get value() {
    console.log('Getting the current value!');
    return this.#count;
  }
  increment() {
    this.#count++;
  }
}
```

**Comment by jogibear9988** [comment]
Yes, but the name of the interface/class in estree is PropertyDefinition

**Comment by jogibear9988** [comment]
everything from this fork is in esprima-next, but maybe in other form
